name: cashir
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  carousel_slider: ^4.1.1
  contained_tab_bar_view: ^0.8.0
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  dartz: ^0.10.1
  date_time_picker: ^2.1.0
  dio: ^4.0.6
  dotted_border: ^2.0.0+2
  draggable_home: ^1.0.3
  equatable: ^2.0.3
  firebase_core: ^1.20.1
  firebase_messaging: ^12.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.1.0
  flutter_svg: ^1.1.3
  get_it: ^7.2.0
  http: ^0.13.5
  internet_connection_checker: ^0.0.1+4
  scroll_navigation: ^1.3.2
  shared_preferences: ^2.0.15


  url_launcher: ^6.1.5





dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lang/ar.json
    - lang/en.json
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 200
